blank_issues_enabled: false
contact_links:
  - name: Report a code of conduct concern
    url: https://github.com/typovrak/nixos/blob/main/.github/CODE_OF_CONDUCT.md#-reporting-issues
    about: Please report conduct issues privately. See our code of conduct.
